In [8]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
dists = np.sqrt(np.sum(np.square(b), axis = 1) + np.transpose([np.sum(np.square(a), axis = 1)]) - 2*np.dot(a, b.T))
print(a.shape)
print(np.square(a))
print(b.shape)
print(dists)

(2, 3)
[[ 1  4  9]
 [16 25 36]]
(4, 3)
[[ 0.          5.19615242 10.39230485 15.58845727]
 [ 5.19615242  0.          5.19615242 10.39230485]]


In [4]:
print(np.sum(np.square(a), axis = 1))


[14 77]


In [14]:
temp = np.sum(np.square(a), axis = 1) + np.transpose([np.sum(np.square(b), axis = 1)])
print(np.sum(np.square(a), axis = 1))
print(np.transpose([np.sum(np.square(b), axis = 1)]))
print(temp)

[14 77]
[[ 14]
 [ 77]
 [194]
 [365]]
[[ 28  91]
 [ 91 154]
 [208 271]
 [379 442]]


In [15]:
x = np.array([3,1,2]) 
print(np.argsort(x))

[1 2 0]


In [19]:
idx = np.argsort(x)[:2]
print(np.argsort(x)[:2])

[1 2]


In [20]:
print(x[idx])

[1 2]


In [21]:
print(type(x[idx]))

<class 'numpy.ndarray'>
